# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(16181C)
$foreground = rgb(D7D9DE)
$color0 = rgb(3D3F44)
$color1 = rgb(28303F)
$color2 = rgb(39404D)
$color3 = rgb(494F5B)
$color4 = rgb(595E6A)
$color5 = rgb(6A6E78)
$color6 = rgb(6A6E78)
$color7 = rgb(BEC0C7)
$color8 = rgb(85868B)
$color9 = rgb(364153)
$color10 = rgb(4B5567)
$color11 = rgb(61697A)
$color12 = rgb(777E8D)
$color13 = rgb(8D92A0)
$color14 = rgb(8D92A0)
$color15 = rgb(BEC0C7)
