# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D7D9DE
background         #16181C
cursor             #9197A2

active_tab_foreground     #16181C
active_tab_background     #D7D9DE
inactive_tab_foreground   #D7D9DE
inactive_tab_background   #16181C

active_border_color   #D7D9DE
inactive_border_color #16181C
bell_border_color     #28303F

color0      #3D3F44
color1		#28303F
color2		#39404D
color3		#494F5B
color4		#595E6A
color5		#6A6E78
color6		#6A6E78
color7		#BEC0C7
color8		#85868B
color9		#364153
color10		#4B5567
color11		#61697A
color12		#777E8D
color13		#8D92A0
color14		#8D92A0
color15		#BEC0C7
